macro (add_sources)
    file (RELATIVE_PATH _relPath "${PROJECT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
    foreach (_src ${ARGN})
        if (_relPath)
            list (APPEND ENGINE_SOURCE "${_relPath}/${_src}")
        else()
            list (APPEND ENGINE_SOURCE "${_src}")
        endif()
    endforeach()
    if (_relPath)
        # propagate SRCS to parent directory
        set (ENGINE_SOURCE ${ENGINE_SOURCE} PARENT_SCOPE)
    endif()
endmacro()

macro (add_include_dir)
    file (RELATIVE_PATH _relPath "${PROJECT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
    foreach (_src ${ARGN})
        string(REPLACE "${PROJECT_SOURCE_DIR}/" "" FOLDERNAME "${_src}")
        list (APPEND INCLUDE_PATHS "${FOLDERNAME}")
    endforeach()
    if (_relPath)
        # propagate SRCS to parent directory
        set (INCLUDE_PATHS ${INCLUDE_PATHS} PARENT_SCOPE)
    endif()
endmacro()